version: "3"
services:
  web:
    build: .
    image: anoosha1221/recipe-react-app
    ports:
      - 3001:3000
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
    environment:
      - REACT_APP_BASE_URL=http://localhost:4000/recipebook
    command: npm start
    networks:
      - recipe-book-network
networks:
  recipe-book-network:
    name: recipe-book-network
