services:
  web:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
    environment:
      - REACT_APP_BASE_URL=http://localhost:3000/recipebook
    command: npm start
    networks:
      - recipe-book-network
networks:
  recipe-book-network:
    name: recipe-book-network
