services:
  web:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
    env_file:
      - .env
    command: npm start
    networks:
      - recipe-book-network
networks:
  recipe-book-network:
    name: recipe-book-network
