name: RecipeBook React
run-name: RecipeBook Frontend
on:
  push:
    branches:
      - main
      - recipeBook-version-1
  pull_request:
    branches:
      - main
jobs:
  Workflow-for-RecipeBook-Frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: env setup
        run: |
          DATABASE_URL = MyURL
      - name: Run tests
        run: npm run test -- --watchAll=false
      - name: Build the React app
        run: npm run build
